eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
server:
  port: 8094
spring:
  application:
    name: service-feign

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html